### ISSUE TITLE
Repurpose and rename Revise status

### ISSUE THREAD

**Issue by mauroz77** [PDCMFinder/pdcm-admin-api#69]
## Description

As a curator, I want to identify mappings that are in a status that need to be reviewed because of two reasons:
- The mapping was done automatically so it needs to be reviewed before being moved to Approved.
- The mapping needs a second check because it might be incorrect or another ontology term is more suitable.

## Proposal
To repurpose the status `Revise` so it not only is used to "double-check" when a mapped entity seems odd but also as the status that an automatically mapped term gets, as a previous step before being "totally accepted" as a mapped term. Also, to rename it to `Review`.

**Comment by zperova** [comment]
the status Review will be assigned to all mappings done automatically and to mappings that are deemed to need revision by a curator. Once Review mappings are curated they will be moved to Approved status.

**Comment by mauroz77** [comment]
@zperova Done
